[[redirects]]
  from = "/portfolio"
  to = "/portfolio.html"
  status = 200

[[redirects]]
  from = "/iletisim"
  to = "/iletisim.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200
